version: "3"
services:
  db: 
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: mesh
      MYSQL_PASSWORD: mesh
      MYSQL_DATABASE: mesh
      MYSQL_USER: mesh
    volumes:
      - ./.persistence/db:/var/lib/mysql

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 0.0.0.0:8080:8080

  nginx:
    image: "nginx:alpine"
    ports:
      - 0.0.0.0:443:443
      - 0.0.0.0:8443:8443
      - 0.0.0.0:9443:9443
    volumes:
      - ./nginx:/etc/nginx
      - ./ssl/dhparam.pem:/etc/ssl/dhparam.pem
    depends_on:
      - app
